export const DEFAULT_CATEGORY = Object.freeze({
  none: '',
  arms: 'Arms',
  back: 'Back',
  biceps: 'Biceps',
  cardio: 'Cardio',
  chest: 'Chest',
  core: 'Core',
  legs: 'Legs',
  shoulders: 'Shoulders',
  triceps: 'Triceps',
  compound: 'Compound',
  conditioning: 'Conditioning',
  hiit: 'HIIT',
  event: 'Event',
  misc: 'Miscellaneous',
})

export const DEFAULT_EQUIPMENT = Object.freeze({
  none: '',
  barbell: 'Barbell',
  dumbbell: 'Dumbbell',
  kettlebell: 'Kettlebell',
  machine: 'Machine',
  cableMachine: 'Cable Machine',
  cardioMachine: 'Cardio Machine',
  weightMachine: 'Weight Machine',
  bodyWeight: 'Body Weight',
  bands: 'Resistance Bands',
  custom: 'Custom',
})

export const DEFAULT_DESCRIPTIONS = Object.freeze({
  positionStanding: 'Execute standing.',
  positionSeated: 'Execute sitting down.',
  positionBack: 'Execute on your back.',
  positionStomach: 'Execute on your stomach.',
  positionSide: 'Execute on your side.',
  volumeVeryLow: 'Do 1-3 sets of 5 reps.',
  volumeLow: 'Do 3-5 sets of 5-8 reps.',
  volumeMed: 'Do 3-5 sets of 8-12 reps.',
  volumeHigh: 'Do 3-5 sets of 12-15 reps.',
  volumeVeryHigh: 'Do 3-5 sets of 15-20 reps.',
  braceCore: 'Brace your core.',
  dropSets: 'Drop sets.',
  pyramidSets: 'Pyramid sets.',
  warmup: 'Spend a few minutes warming up.',
  cooldown: 'Spend a few minutes cooling down.',
  conditioning: 'Jumping jacks, mountain climbers, burpees, or other cardio exercise with or without weights.',
  stretching: 'Spend a few minutes stretching muscles you have or will use.',
  // Need descriptions!
})

export const DEFAULT_EXERCISE_NAME = Object.freeze({
  // CARDIO
  warmup: 'Warmup',
  cooldown: 'Cooldown',
  conditioning: 'Conditioning',
  jumpingJacks: 'Jumping Jacks',
  mountainClimbers: 'Mountain Climbers',
  highKnees: 'High Knees',
  burpees: 'Burpees',
  standingCrunches: 'Standing Crunches',
  treadmill: 'Treadmill',
  elliptical: 'Elliptical',
  stairStepper: 'Stair Stepper',
  straightLunges: 'Straight Lunges',
  sideLunges: 'Side Lunges',
  // MISC
  stretching: 'Stretching',
  // CHEST
  benchPress: 'Bench Press',
  inclineBenchPress: 'Incline Bench Press',
  declineBenchPress: 'Decline Bench Press',
  chestFlys: 'Chest Flys',
  diamondPushups: 'Diamond Push-ups',
  militaryPushups: 'Military Push-ups',
  standardPushups: 'Standard Push-ups',
  widePushups: 'Wide Push-ups',
  pikePushups: 'Pike Push-ups',
  layingOverheadStraightArms: 'Laying Overhead Straight Arms',
  chestSidePulls: 'Chest Side Pulls',
  // SHOULDERS
  overheadPress: 'Overhead Press',
  diagonalArmRaises: 'Diagonal Arm Raises',
  sideArmRaises: 'Side Arm Raises',
  frontArmRaises: 'Front Arm Raises',
  frontSideArmRaises: 'Front and Side Arm Raises',
  threeWayArmRaises: '3-Way Arm Raises',
  shoulderShrugs: 'Shoulder Shrugs',
  // TRICEPS
  skullCrushers: 'Skull Crushers',
  tricepKickbacks: 'Tricep Kickbacks',
  tricepPulldowns: 'Tricep Pulldowns',
  tricepOverheadExt: 'Tricep Overhead Extentions',
  layingTricepExt: 'Laying Tricep Extension',
  dips: 'Dips',
  // BACK
  bentOverBackFlys: 'Bent Over Back Flys',
  bentOverRows: 'Bent Over Rows',
  stiffLegDeadlift: 'Stiff Leg Deadlift',
  deadlift: 'Deadlift',
  widePullups: 'Wide Overhand Pull-ups',
  chinups: 'Chin-ups',
  hammerPullups: 'Hammer Grip Pull-ups',
  facePulls: 'Face Pulls',
  tRows: 'T-Rows',
  // BICEPS
  overhandCurls: 'Overhand Bicep Curls',
  underhandCurls: 'Underhand Bicep Curls',
  hammerCurls: 'Hammer Bicep Curls',
  // LEGS
  squats: 'Squats',
  legCurls: 'Leg Curls',
  legExt: 'Leg Extensions',
  calfRaises: 'Calf Raises',
  hipThrusters: 'Hip Thrusters',
  // CORE
  obliqueSideBend: 'Oblique Side Bends',
  abdominalCrunch: 'Abdominal Crunch',
  russianTwist: 'Russian Twist',
})