export const DEFAULT_CATEGORY = Object.freeze({
  none: '',
  arms: 'Arms',
  back: 'Back',
  biceps: 'Biceps',
  cardio: 'Cardio',
  chest: 'Chest',
  core: 'Core',
  legs: 'Legs',
  shoulders: 'Shoulders',
  triceps: 'Triceps',
  compound: 'Compound',
  misc: 'Miscellaneous',
})

export const DEFAULT_EQUIPMENT = Object.freeze({
  none: '',
  barbell: 'Barbell',
  dumbbell: 'Dumbbell',
  kettlebell: 'Kettlebell',
  machine: 'Machine',
  cableMachine: 'Cable Machine',
  cardioMachine: 'Cardio Machine',
  weightMachine: 'Weight Machine',
  weightVest: 'Weight Vest',
  bands: 'Resistance Bands',
  chains: 'Chains',
})

export const DEFAULT_DESCRIPTION = Object.freeze({
  braceCore: 'Brace your core.',
})

export const DEFAULT_PLAN = Object.freeze({
  none: '',
  unspecified: 'Unspecified',
})

export const DEFAULT_EXERCISE = Object.freeze({
  farmersWalk: {
    name: 'Farmer\'s Walk',
    description: `${DEFAULT_DESCRIPTION.braceCore} Walk with weights in each hand at your sides.`,
    category: DEFAULT_CATEGORY.compound,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '1-3',
      weight: '30-60',
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  warmup: {
    name: 'Warmup',
    description: 'Spend a few minutes warming up.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '5-10',
      distance: null,
    },
  },
  cooldown: {
    name: 'Cooldown',
    description: 'Spend a few minutes cooling down.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '5-10',
      distance: null,
    },
  },
  jumpingJacks: {
    name: 'Jumping Jacks',
    description: 'Alternate jumping your legs wide to narrow and arms wide then back to your side.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  mountainClimbers: {
    name: 'Mountain Climbers',
    description: 'Alternate bringing your knees close to your chin while in plank position.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  highKnees: {
    name: 'High Knees',
    description: 'Alternate bringing your knees up quickly while standing.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  burpees: {
    name: 'Burpees',
    description: 'Starting from plank, do a push-up, jump your legs forward, then jump with high knees, and return to plank position.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  highArmsAlternatingKnees: {
    name: 'High Arms Alternating Knees',
    description: 'With arms in the air, alternate one knee up to your waist as you crunch down with your arms.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  treadmill: {
    name: 'Treadmill',
    description: 'Walking, jogging, running, or sprints.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [DEFAULT_EQUIPMENT.cardioMachine],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '20-60',
      distance: null,
    },
  },
  elliptical: {
    name: 'Elliptical',
    description: 'Standard elliptical machine.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [DEFAULT_EQUIPMENT.cardioMachine],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '20-60',
      distance: null,
    },
  },
  stairStepper: {
    name: 'Stair Stepper',
    description: 'Standard stair stepper machine.',
    category: DEFAULT_CATEGORY.cardio,
    equipment: [DEFAULT_EQUIPMENT.cardioMachine],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '20-60',
      distance: null,
    },
  },
  straightLunges: {
    name: 'Straight Lunges',
    description: 'Standing or walking straight lunges.',
    category: DEFAULT_CATEGORY.misc,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  sideLunges: {
    name: 'Side Lunges',
    description: 'Standing alternating side lunges.',
    category: DEFAULT_CATEGORY.misc,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '1-2',
      distance: null,
    },
  },
  stretching: {
    name: 'Stretching',
    description: 'Spend a few minutes stretching muscles you have or plan to use.',
    category: DEFAULT_CATEGORY.misc,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: '5-10',
      distance: null,
    },
  },
  benchPress: {
    name: 'Bench Press',
    description: `${DEFAULT_DESCRIPTION.braceCore} Push weight from chest to above neck.`,
    category: DEFAULT_CATEGORY.chest,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3-5',
      weight: '40-300',
      reps: '5-8',
      duration: null,
      distance: null,
    },
  },
  inclineBenchPress: {
    name: 'Incline Bench Press',
    description: `${DEFAULT_DESCRIPTION.braceCore} Push weight above chest while at an incline.`,
    category: DEFAULT_CATEGORY.chest,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3-5',
      weight: '20-200',
      reps: '5-8',
      duration: null,
      distance: null,
    },
  },
  declineBenchPress: {
    name: 'Decline Bench Press',
    description: `${DEFAULT_DESCRIPTION.braceCore} Push weight above chest while at a decline.`,
    category: DEFAULT_CATEGORY.chest,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3-5',
      weight: '40-300',
      reps: '5-8',
      duration: null,
      distance: null,
    },
  },
  chestFlys: {
    name: 'Bench Chest Flyes',
    description: '',
    category: DEFAULT_CATEGORY.chest,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3-5',
      weight: '15-30',
      reps: '8-12',
      duration: null,
      distance: null,
    },
  },
  diamondPushups: {
    name: 'Diamond Push-ups',
    description: 'Place hands next to eachother under chest while in plank position and push up.',
    category: DEFAULT_CATEGORY.chest,
    equipment: [],
    plan: {
      sets: '3',
      weight: null,
      reps: '10-20',
      duration: null,
      distance: null,
    },
  },
  militaryPushups: {
    name: 'Military Push-ups',
    description: 'Place hands under shoulders while in plank position and push up keeping the elbows next to your body.',
    category: DEFAULT_CATEGORY.chest,
    equipment: [],
    plan: {
      sets: '3',
      weight: null,
      reps: '15-20',
      duration: null,
      distance: null,
    },
  },
  standardPushups: {
    name: 'Standard Push-ups',
    description: 'Place hands slightly outside of shoulders while in plank position and push up.',
    category: DEFAULT_CATEGORY.chest,
    equipment: [],
    plan: {
      sets: '3',
      weight: null,
      reps: '15-20',
      duration: null,
      distance: null,
    },
  },
  widePushups: {
    name: 'Wide Push-ups',
    description: 'Place hands wide outside of shoulders while in plank position and push up.',
    category: DEFAULT_CATEGORY.chest,
    equipment: [],
    plan: {
      sets: '3',
      weight: null,
      reps: '15-20',
      duration: null,
      distance: null,
    },
  },
  pikePushups: {
    name: 'Pike Push-ups',
    description: 'Push up and down with the arms while in downward dog position.',
    category: DEFAULT_CATEGORY.chest,
    equipment: [],
    plan: {
      sets: '3',
      weight: null,
      reps: '10-20',
      duration: null,
      distance: null,
    },
  },
  layingOverheadStraightArms: {
    name: 'Laying Overhead Straight Arms',
    description: 'Extend weight behind head and bring back above head in arc motion while laying upper back on a bench.',
    category: DEFAULT_CATEGORY.chest,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3',
      weight: '15-30',
      reps: '10-15',
      duration: null,
      distance: null,
    },
  },
  chestSidePulls: {
    name: 'Chest Side Pulls',
    description: 'Stand and pull weight to stomach while keeping elbow locked to your side.',
    category: DEFAULT_CATEGORY.chest,
    equipment: [DEFAULT_EQUIPMENT.cableMachine],
    plan: {
      sets: '3',
      weight: '10-30',
      reps: '10-15',
      duration: null,
      distance: null,
    },
  },
  overheadPress: {
    name: 'Overhead Press',
    description: 'Press weight above head while seated or standing.',
    category: DEFAULT_CATEGORY.shoulders,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '1-3',
      weight: '20-80',
      reps: '5-8',
      duration: null,
      distance: null,
    },
  },
  diagonalArmRaises: {
    name: 'Diagonal Arm Raises',
    description: 'Raise straight arms up at an angle from your body.',
    category: DEFAULT_CATEGORY.shoulders,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3',
      weight: '5-20',
      reps: '10-15',
      duration: null,
      distance: null,
    },
  },
  sideArmRaises: {
    name: 'Side Arm Raises',
    description: 'Raise straight arms up from the sides of your body.',
    category: DEFAULT_CATEGORY.shoulders,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3',
      weight: '5-20',
      reps: '10-15',
      duration: null,
      distance: null,
    },
  },
  frontArmRaises: {
    name: 'Front Arm Raises',
    description: 'Raise straight arms up in front of your body.',
    category: DEFAULT_CATEGORY.shoulders,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3',
      weight: '5-20',
      reps: '10-15',
      duration: null,
      distance: null,
    },
  },
  shoulderShrugs: {
    name: 'Shoulder Shrugs',
    description: `${DEFAULT_DESCRIPTION.braceCore} Lift with your shoulders while standing with weight at your sides.`,
    category: DEFAULT_CATEGORY.shoulders,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3-5',
      weight: '30-300',
      reps: '5-8',
      duration: null,
      distance: null,
    },
  },
  tricepKickbacks: {
    name: 'Tricep Kickbacks',
    description: 'Bend at waist while stand and extend arms backward.',
    category: DEFAULT_CATEGORY.triceps,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3',
      weight: '10-25',
      reps: '8-12',
      duration: null,
      distance: null,
    },
  },
  tricepPulldowns: {
    name: 'Tricep Pulldowns',
    description: 'Pull cables directly down and hold briefly while standing.',
    category: DEFAULT_CATEGORY.triceps,
    equipment: [DEFAULT_EQUIPMENT.cableMachine],
    plan: {
      sets: '3',
      weight: '15-30',
      reps: '8-12',
      duration: null,
      distance: null,
    },
  },
  tricepOverheadExt: {
    name: 'Tricep Overhead Extentions',
    description: 'Face away from cable machine and pull weight overhead.',
    category: DEFAULT_CATEGORY.triceps,
    equipment: [DEFAULT_EQUIPMENT.cableMachine],
    plan: {
      sets: '3',
      weight: '15-30',
      reps: '8-12',
      duration: null,
      distance: null,
    },
  },
  layingTricepExt: {
    name: 'Laying Tricep Extension',
    description: 'Hold weight above head while laying down and bend elbows to lower weight behind head.',
    category: DEFAULT_CATEGORY.triceps,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3',
      weight: '15-30',
      reps: '8-12',
      duration: null,
      distance: null,
    },
  },
  dips: {
    name: 'Dips',
    description: 'Hold body up by arms and lower yourself down and back up.',
    category: DEFAULT_CATEGORY.triceps,
    equipment: [],
    plan: {
      sets: '3',
      weight: null,
      reps: '8-12',
      duration: null,
      distance: null,
    },
  },
  bentOverBackFlys: {
    name: 'Bent Over Back Flys',
    description: 'Lean over with arms hanging down and pull arms up in a wide motion while bringing your shoulder blades together.',
    category: DEFAULT_CATEGORY.back,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: '3',
      weight: '12-30',
      reps: '8-12',
      duration: null,
      distance: null,
    },
  },
  // -------------------------- WORK IN PROGRESS ---------------------------------------------------
  bentOverRows: {
    name: 'Bent Over Rows',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  stiffLegDeadlift: {
    name: 'Stiff Leg Deadlift',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  deadlift: {
    name: 'Deadlift',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  widePullups: {
    name: 'Wide Overhand Pull-ups',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  chinups: {
    name: 'Chin-ups',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  hammerPullups: {
    name: 'Hammer Grip Pull-ups',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  facePulls: {
    name: 'Face Pulls',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [DEFAULT_EQUIPMENT.cableMachine],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  tRows: {
    name: 'T-Rows',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.back,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    },
  },
  overhandCurls: {
    name: 'Overhand Bicep Curls',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.biceps,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  underhandCurls: {
    name: 'Underhand Bicep Curls',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.biceps,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  hammerCurls: {
    name: 'Hammer Bicep Curls',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.biceps,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  squats: {
    name: 'Squats',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.legs,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  legCurls: {
    name: 'Leg Curls',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.legs,
    equipment: [DEFAULT_EQUIPMENT.weightMachine],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  legExt: {
    name: 'Leg Extensions',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.legs,
    equipment: [DEFAULT_EQUIPMENT.weightMachine],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  calfRaises: {
    name: 'Calf Raises',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.legs,
    equipment: [DEFAULT_EQUIPMENT.dumbbell, DEFAULT_EQUIPMENT.cableMachine],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  hipThrusters: {
    name: 'Hip Thrusters',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.legs,
    equipment: [DEFAULT_EQUIPMENT.barbell, DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  plank: {
    name: 'Plank',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.core,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  obliqueSideBend: {
    name: 'Oblique Side Bends',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.core,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  abdominalCrunch: {
    name: 'Abdominal Crunch',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.core,
    equipment: [],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
  russianTwist: {
    name: 'Russian Twist',
    description: 'XXXXX',
    category: DEFAULT_CATEGORY.core,
    equipment: [DEFAULT_EQUIPMENT.dumbbell],
    plan: {
      sets: null,
      weight: null,
      reps: null,
      duration: null,
      distance: null,
    }, 
  },
})